name: Publish Docker Image

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 2 * * *'  # 每日凌晨2点自动执行

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/nezhahq/nezha/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
          echo "Latest tag: $LATEST_TAG"
          echo "::set-output name=latest_tag::$LATEST_TAG"

      - name: Read current version
        id: read_version
        run: |
          CURRENT_VERSION=$(cat version)
          echo "Current version: $CURRENT_VERSION"
          echo "::set-output name=current_version::$CURRENT_VERSION"

      - name: Compare versions
        id: compare_versions
        run: |
          if [[ "${{ steps.get_latest_tag.outputs.latest_tag }}" > "${{ steps.read_version.outputs.current_version }}" ]]; then
            echo "New version available, continuing..."
            echo "::set-output name=should_build::true"
          else
            echo "No new version available, stopping..."
            echo "::set-output name=should_build::false"
          fi

      - name: Set up Docker Buildx
        if: steps.compare_versions.outputs.should_build == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: steps.compare_versions.outputs.should_build == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.compare_versions.outputs.should_build == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/argo-nezha:latest

      - name: Update version file
        if: steps.compare_versions.outputs.should_build == 'true'
        run: |
          echo "${{ steps.get_latest_tag.outputs.latest_tag }}" > version
